---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.25.0
    hooks:
      - id: yamllint
        entry: yamllint -c .github/workflow-config/.yamllint.yml
        types:
          - yaml
#  - repo: 'https://github.com/sean-m-sullivan/ansible-lint.git'
#    rev: 4.3.8
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v4.3.7
    hooks:
      # see discussions here about what arguments are used, and behavior
      # https://github.com/ansible/ansible-lint/issues/649
      # Roles will trigger an "unknown file type"
      # https://github.com/ansible/ansible-lint/issues/808
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: >-
          ansible-lint -vp -c .github/workflow-config/.ansiblelint.yml
          --exclude=roles/master_role_example/
          --exclude=.github/workflows/testing_playbooks.yml
          --exclude=.github/workflows/testing_playbooks_awx.yml
          --exclude=playbooks/collections/requirements.yml
          --exclude=playbooks/tower_configs/ssh_private_key.yml
          --exclude=playbooks/tower_configs/tower_applications.yml
          --exclude=playbooks/tower_configs/tower_auth.yml
          --exclude=playbooks/tower_configs/tower_credential_input_sources.yml
          --exclude=playbooks/tower_configs/tower_credential_types.yml
          --exclude=playbooks/tower_configs/tower_credentials.yml
          --exclude=playbooks/tower_configs/tower_groups.yml
          --exclude=playbooks/tower_configs/tower_hosts.yml
          --exclude=playbooks/tower_configs/tower_instance_groups.yml
          --exclude=playbooks/tower_configs/tower_inventories.yml
          --exclude=playbooks/tower_configs/tower_inventory_sources.yml
          --exclude=playbooks/tower_configs/tower_labels.yml
          --exclude=playbooks/tower_configs/tower_notifications.yml
          --exclude=playbooks/tower_configs/tower_organizations.yml
          --exclude=playbooks/tower_configs/tower_projects.yml
          --exclude=playbooks/tower_configs/tower_rbac.yml
          --exclude=playbooks/tower_configs/tower_schedule.yml
          --exclude=playbooks/tower_configs/tower_settings.yml
          --exclude=playbooks/tower_configs/tower_settings_individuale.yml
          --exclude=playbooks/tower_configs/tower_teams.yml
          --exclude=playbooks/tower_configs/tower_templates.yml
          --exclude=playbooks/tower_configs/tower_user_accounts.yml
          --exclude=playbooks/tower_configs/tower_workflows.yml
          --exclude=playbooks/tower_configs_export_model/credential_types_export.yml
          --exclude=playbooks/tower_configs_export_model/credentials_export.yml
          --exclude=playbooks/tower_configs_export_model/inventory_export.yml
          --exclude=playbooks/tower_configs_export_model/inventory_sources_export.yml
          --exclude=playbooks/tower_configs_export_model/job_templates_export.yml
          --exclude=playbooks/tower_configs_export_model/notifications_templates_export.yml
          --exclude=playbooks/tower_configs_export_model/organizations_export.yml
          --exclude=playbooks/tower_configs_export_model/projects_export.yml
          --exclude=playbooks/tower_configs_export_model/teams_export.yml
          --exclude=playbooks/tower_configs_export_model/tower_workflows.yml
          --exclude=playbooks/tower_configs_export_model/users_export.yml
          --exclude=roles/applications/tests/collections/requirements.yml
          --exclude=roles/credential_input_sources/tests/collections/requirements.yml
          --exclude=roles/credential_types/tests/collections/requirements.yml
          --exclude=roles/credentials/tests/collections/requirements.yml
          --exclude=roles/groups/tests/collections/requirements.yml
          --exclude=roles/hosts/tests/collections/requirements.yml
          --exclude=roles/inventories/tests/configs/tower-inventories.yml
          --exclude=roles/inventory_sources/tests/configs/tower-inventory-sources.yml
          --exclude=roles/job_templates/tests/collections/requirements.yml
          --exclude=roles/labels/tests/configs/tower_labels.yml
          --exclude=roles/license/tests/collections/requirements.yml
          --exclude=roles/notification_templates/tests/collections/requirements.yml
          --exclude=roles/organizations/tests/collections/requirements.yml
          --exclude=roles/projects/tests/collections/requirements.yml
          --exclude=roles/schedules/tests/collections/requirements.yml
          --exclude=roles/teams/tests/configs/tower_teams.yml
          --exclude=roles/tower_role/tests/collections/requirements.yml
          --exclude=roles/tower_settings/tests/configs/tower_settings.yml
          --exclude=roles/users/tests/collections/requirements.yml
          --exclude=roles/workflow_job_templates/tests/collections/requirements.yml
          --exclude=roles/workflow_job_templates/tests/yaml/extra_vars.yaml
          --exclude=roles/workflow_job_templates/tests/yaml/tower_workflows.yml
