  ---
  repos:
    - repo: 'https://github.com/pre-commit/pre-commit-hooks'
      rev: v3.2.0
      hooks:
        - id: end-of-file-fixer
        - id: trailing-whitespace
    - repo: 'https://github.com/adrienverge/yamllint.git'
      rev: v1.25.0
      hooks:
        - id: yamllint
          entry: yamllint -c .github/workflow-config/.yamllint.yml
          types:
            - yaml
    - repo: 'https://github.com/sean-m-sullivan/ansible-lint.git'
      rev: 4.3.8
      hooks:
        # see discussions here about what arguments are used, and behavior
        # https://github.com/ansible/ansible-lint/issues/649
        # Roles will trigger an "unknown file type"
        # https://github.com/ansible/ansible-lint/issues/808
        - id: ansible-lint
          pass_filenames: false
          always_run: true
          entry: >-
            ansible-lint -vp -c .github/workflow-config/.ansiblelint.yml
            --exclude=roles/master_role_example
