---
- name: Playbook to configure ansible tower post installation
  hosts: localhost
  connection: local
  vars:
    workflow_job_templates_secure_logging: false
    tower_validate_certs: false
  collections:
    - awx.awx
    - redhat_cop.tower_configuration
  # Define following vars here, or in tower_configs/tower_auth.yml
  # tower_hostname: ansible-tower-web-svc-test-project.example.com
  # tower_username: admin
  # tower_password: changeme
  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs_export_model
        ignore_files: [README.md]
        extensions: ["yml"]
  roles:
    - {role: job_templates, when: tower_templates is defined, tags: job_templates}
    - {role: workflow_job_templates, when: tower_workflows is defined}
    - {role: notification_templates, when: tower_notifications is defined, tags: notification_templates}
